[pytest]
filterwarnings =
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore:import 'orangecanvas.utils.localization':DeprecationWarning
    ignore:.*urllib3.*match a supported version.*:
